server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://10.211.55.7:3306/my_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-handlers-package: study.config.mybatis.handler